import Foundation
import SwiftUI
import Combine

@MainActor
class GlobalChatViewModel: ObservableObject {
    @Published var inputText: String = ""
    @Published var isRecording: Bool = false
    @Published var isFocused: Bool = false
    @Published var isExpanded: Bool = false
    @Published var isProcessing: Bool = false
    @Published var animationPhase: Int = 0
    @Published var shouldPresentNewChatOverlay: Bool = false
    
    // Reference to the sessions view model (should be injected from parent/app coordinator)
    var chatSessionsViewModel: ChatSessionsViewModel?
    weak var taskViewModel: TaskViewModel?

    // Callback to trigger UI transition to NewChatScreen
    var onStartNewChat: (() -> Void)?
    
    /// Start a new chat session with the user's prompt
    func startNewChatSession(with prompt: String) {
        guard let sessionsVM = chatSessionsViewModel else { return }
        let userMessage = ChatMessage(text: prompt, isUser: true)
        // Create a new session with only the user's initial message.
        // The session ID will be generated by ChatSession's init.
        var newSession = ChatSession(title: "New Chat", messages: [userMessage])
        
        sessionsVM.sessions.insert(newSession, at: 0)
        sessionsVM.currentSession = newSession
        let sessionID = newSession.id // Capture session ID for async use
        
        inputText = ""
        onStartNewChat?() // Optionally trigger UI transition
        isProcessing = true

        // For a new chat, conversation history is empty.
        // The ClaudeLLMService.detectIntentAndRespond will prepend the system prompt.
        let conversationHistory: [ClaudeMessage] = []

        ClaudeLLMService.shared.detectIntentAndRespond(userMessageText: prompt, conversationHistory: conversationHistory) { [weak self, weak sessionsVM, weak taskVM = self.taskViewModel] result in
            DispatchQueue.main.async {
                self?.isProcessing = false // Initial processing for LLM response done
                guard let strongSelf = self, let sessionsVM = sessionsVM else {
                    print("[Chat] self or sessionsVM was nil in Claude response handler for new chat")
                    return
                }

                guard let sessionIndex = sessionsVM.sessions.firstIndex(where: { $0.id == sessionID }) else {
                    print("[Chat] Could not find new session index for id: \(sessionID) in Claude response handler")
                    return
                }

                var sessionToUpdate = sessionsVM.sessions[sessionIndex]

                switch result {
                case .success(let intentResponse):
                    let assistantInitialReply = ChatMessage(text: intentResponse.assistant_reply, isUser: false)
                    sessionToUpdate.messages.append(assistantInitialReply)
                    print("[Chat] Claude initial intent-based reply appended to new session \(sessionID): \(intentResponse.assistant_reply)")

                    // Handle task creation intent
                    if intentResponse.intent == .createTask, let taskDetails = intentResponse.task_details {
                        print("[Chat] New Session: Intent to create task recognized. Title: \(taskDetails.title)")
                        guard let taskVM = taskVM else {
                            print("[Chat] TaskViewModel is nil. Cannot create task.")
                            let errorMessage = ChatMessage(text: "[Internal Error: Could not access task creation service.]", isUser: false)
                            sessionToUpdate.messages.append(errorMessage)
                            // No 'return' here, proceed to title generation if needed
                        }
                        if let taskVM = taskVM { // Only proceed if taskVM is available
                            strongSelf.isProcessing = true // Show processing for task creation
                            Task {
                                do {
                                    _ = try await taskVM.createNewTask(title: taskDetails.title, description: taskDetails.description)
                                    print("[Chat] Task '\(taskDetails.title)' created successfully from new session.")
                                    let confirmationMessage = ChatMessage(text: "✅ Task created: \(taskDetails.title)", isUser: false)
                                    // We need to re-fetch sessionIndex if messages array changes in other tasks
                                    if let taskSessionIndex = sessionsVM.sessions.firstIndex(where: { $0.id == sessionID }) {
                                        sessionsVM.sessions[taskSessionIndex].messages.append(confirmationMessage)
                                        sessionsVM.currentSession = sessionsVM.sessions[taskSessionIndex]
                                    }
                                } catch {
                                    print("[Chat] Failed to create task '\(taskDetails.title)' from new session: \(error.localizedDescription)")
                                    let errorMessage = ChatMessage(text: "⚠️ Failed to create task: \(taskDetails.title). Error: \(error.localizedDescription)", isUser: false)
                                    if let taskSessionIndex = sessionsVM.sessions.firstIndex(where: { $0.id == sessionID }) {
                                        sessionsVM.sessions[taskSessionIndex].messages.append(errorMessage)
                                        sessionsVM.currentSession = sessionsVM.sessions[taskSessionIndex]
                                    }
                                }
                                if let taskSessionIndex = sessionsVM.sessions.firstIndex(where: { $0.id == sessionID }) {
                                     sessionsVM.currentSession = sessionsVM.sessions[taskSessionIndex] // Ensure UI updates with task messages
                                }
                                strongSelf.isProcessing = false
                            }
                        }
                    } else if intentResponse.intent == .unknown {
                        print("[Chat] New Session: LLM returned an unknown intent.")
                    }

                    // Update the session in the array and as currentSession
                    sessionsVM.sessions[sessionIndex] = sessionToUpdate
                    sessionsVM.currentSession = sessionToUpdate

                    // Proceed to generate title for the new session
                    // Use the messages now in sessionToUpdate (user prompt + assistant's first reply)
                    let messagesForTitle = sessionToUpdate.messages.map { msg in
                        ClaudeMessage(role: msg.isUser ? "user" : "assistant", content: msg.text)
                    }
                    
                    if !messagesForTitle.isEmpty { // Ensure there are messages to generate a title from
                        ClaudeLLMService.shared.generateTitleForChatSession(messages: messagesForTitle) { titleResult in
                            DispatchQueue.main.async {
                                // Ensure session is still valid and get its latest index
                                guard let titleSessionIndex = sessionsVM.sessions.firstIndex(where: { $0.id == sessionID }) else {
                                    print("[Chat] Session for title generation disappeared.")
                                    return
                                }
                                var sessionForTitleUpdate = sessionsVM.sessions[titleSessionIndex]
                                switch titleResult {
                                case .success(let title):
                                    let trimmedTitle = title.trimmingCharacters(in: .whitespacesAndNewlines)
                                    print("[Chat] Claude generated session title for new session \(sessionID): \(trimmedTitle)")
                                    sessionForTitleUpdate.title = trimmedTitle.isEmpty ? "New Chat" : trimmedTitle
                                case .failure(let error):
                                    print("[Chat] Failed to generate session title for new session \(sessionID): \(error.localizedDescription)")
                                    // Keep default "New Chat" title or whatever was set initially
                                }
                                sessionsVM.sessions[titleSessionIndex] = sessionForTitleUpdate
                                sessionsVM.currentSession = sessionForTitleUpdate // Update UI
                            }
                        }
                    }

                case .failure(let error):
                    let errorMessageText = "[LLM Error: \(error.localizedDescription)]"
                    let errorMessage = ChatMessage(text: errorMessageText, isUser: false)
                    sessionToUpdate.messages.append(errorMessage)
                    sessionsVM.sessions[sessionIndex] = sessionToUpdate
                    sessionsVM.currentSession = sessionToUpdate
                    print("[Chat] Claude error in new session \(sessionID): \(error.localizedDescription)")
                }
            }
        }
    }
    
    /// Called when the user presses send/submit in the global chat input
    func submitText() {
        let text = inputText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return }
        startNewChatSession(with: text)
        shouldPresentNewChatOverlay = true
    }
    
    /// Appends a message to the current session and sends it to the LLM (for use in NewChatScreen)
    func sendMessageToCurrentSession(_ text: String) {
        guard let sessionsVM = chatSessionsViewModel, let currentSess = sessionsVM.currentSession else {
            print("[Chat] No current session or sessionsVM when sending message.")
            return
        }
        print("[Chat] Sending user message to current session: \(text)")
        let userMessage = ChatMessage(text: text, isUser: true)
        
        // Safely capture current session ID for use in async blocks
        let sessionID = currentSess.id

        // Append user message to the session immediately
        if let idx = sessionsVM.sessions.firstIndex(where: { $0.id == sessionID }) {
            sessionsVM.sessions[idx].messages.append(userMessage)
            sessionsVM.currentSession = sessionsVM.sessions[idx] // Ensure currentSession is updated
            print("[Chat] Appended user message to session \(sessionID)")
        } else {
            print("[Chat] Could not find session index for id: \(sessionID) when appending user message")
            return // Early exit if session is not found
        }
        
        inputText = ""
        isProcessing = true

        // Prepare conversation history from the updated session
        // Ensure we get the messages *before* this new one for history, or *including* for context, depending on LLM strategy.
        // For Claude, typically history + current user message is sent as a sequence.
        // The ClaudeLLMService.detectIntentAndRespond will prepend the system prompt.
        let conversationHistory: [ClaudeMessage] = sessionsVM.sessions.first(where: { $0.id == sessionID })?.messages
            .dropLast() // Exclude the message we just added, as it's the 'current' user message
            .map { msg in ClaudeMessage(role: msg.isUser ? "user" : "assistant", content: msg.text) } ?? []

        ClaudeLLMService.shared.detectIntentAndRespond(userMessageText: text, conversationHistory: conversationHistory) { [weak self, weak sessionsVM, weak taskVM = self.taskViewModel] result in
            DispatchQueue.main.async {
                self?.isProcessing = false
                guard let strongSelf = self, let sessionsVM = sessionsVM else {
                    print("[Chat] self or sessionsVM was nil in Claude response handler")
                    return
                }

                guard let sessionIndex = sessionsVM.sessions.firstIndex(where: { $0.id == sessionID }) else {
                    print("[Chat] Could not find session index for id: \(sessionID) in Claude response handler")
                    return
                }

                switch result {
                case .success(let intentResponse):
                    // Add LLM's conversational reply to chat
                    let assistantMessage = ChatMessage(text: intentResponse.assistant_reply, isUser: false)
                    sessionsVM.sessions[sessionIndex].messages.append(assistantMessage)
                    sessionsVM.currentSession = sessionsVM.sessions[sessionIndex]
                    print("[Chat] Appended Claude intent-based reply to session \(sessionID): \(intentResponse.assistant_reply)")

                    // Handle task creation intent
                    if intentResponse.intent == .createTask, let taskDetails = intentResponse.task_details {
                        print("[Chat] Intent to create task recognized. Title: \(taskDetails.title)")
                        guard let taskVM = taskVM else {
                            print("[Chat] TaskViewModel is nil. Cannot create task.")
                            let errorMessage = ChatMessage(text: "[Internal Error: Could not access task creation service.]", isUser: false)
                            sessionsVM.sessions[sessionIndex].messages.append(errorMessage)
                            sessionsVM.currentSession = sessionsVM.sessions[sessionIndex]
                            return
                        }
                        
                        strongSelf.isProcessing = true // Show processing for task creation
                        Task {
                            do {
                                _ = try await taskVM.createNewTask(title: taskDetails.title, description: taskDetails.description)
                                print("[Chat] Task '\(taskDetails.title)' created successfully.")
                                let confirmationMessage = ChatMessage(text: "✅ Task created: \(taskDetails.title)", isUser: false)
                                sessionsVM.sessions[sessionIndex].messages.append(confirmationMessage)
                            } catch {
                                print("[Chat] Failed to create task '\(taskDetails.title)': \(error.localizedDescription)")
                                let errorMessage = ChatMessage(text: "⚠️ Failed to create task: \(taskDetails.title). Error: \(error.localizedDescription)", isUser: false)
                                sessionsVM.sessions[sessionIndex].messages.append(errorMessage)
                            }
                            sessionsVM.currentSession = sessionsVM.sessions[sessionIndex] // Update UI
                            strongSelf.isProcessing = false
                        }
                    } else if intentResponse.intent == .unknown {
                        print("[Chat] LLM returned an unknown intent or failed to parse its own JSON correctly.")
                        // The assistant_reply is already added. Consider if specific error message is needed.
                    }

                case .failure(let error):
                    let errorMessageText = "[LLM Error: \(error.localizedDescription)]"
                    let errorMessage = ChatMessage(text: errorMessageText, isUser: false)
                    sessionsVM.sessions[sessionIndex].messages.append(errorMessage)
                    sessionsVM.currentSession = sessionsVM.sessions[sessionIndex]
                    print("[Chat] Claude error: \(error.localizedDescription)")
                }
            }
        }
    }
    
    func startRecording() {
        isRecording = true
    }
    
    func stopRecording() {
        isRecording = false
    }
    
    func dismissKeyboard() {
        isFocused = false
    }
}
